[connections.supabase]
SUPABASE_URL = "https://eyzghgfqffefuippsibu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5emdoZ2ZxZmZlZnVpcHBzaWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTc0NzU5MzUsImV4cCI6MjAzMzA1MTkzNX0.jMZRvGwHMeFI7gwSy-bWcQ49hIbh3vj5ZoeNvUkFo0w"